const name= ["pramesh","aditya","deepika"];
name.forEach(names=> {
    console.log(names);
});


const student= ["pramesh","aditya","deepika"];
const newstudent=student.map((newname) =>{
return newname + "amrit";
});
console.log(newstudent);

const fruits = [
    "Apple",
    "Banana",
    "Orange",
    "Grape",
    "Strawberry",
    "Pineapple",
    "Watermelon",
    "Kiwi",
    "Mango",
    "Peach",
    "Pear",
    "Cherry",
    "Blueberry",
    "Raspberry",
    "Cantaloupe",
    "Plum",
    "Apricot",
    "Blackberry",
    "Coconut",
    "Lemon",
    "Lime",
    "Grapefruit",
    "Pomegranate",
    "Avocado",
    "Fig",
    "Passionfruit",
    "Papaya",
    "Lychee",
    "Guava",
    "Dragonfruit",
    "Cranberry",
    "Tangerine",
    "Nectarine",
    "Date",
    "Persimmon",
    "Kumquat",
    "Melon",
    "Starfruit",
    "Honeydew",
    "Rambutan",
    "Mulberry",
    "Jackfruit",
    "Durian",
    "Gooseberry",
    "Pawpaw",
    "Quince",
    "Açaí",
    "Carambola",
    "Feijoa",
    "Loquat",
    "Soursop",
    "Tamarind",
    "Ugli Fruit",
    "Ackee",
    "Noni Fruit",
    "Plantain",
    "Yuzu",
    "Feijoa",
    "Black Currant",
    "Red Currant",
    "White Currant",
    "Cherimoya",
    "Prickly Pear",
    "Guanabana",
    "Pitaya",
    "Atemoya",
    "Pummelo",
    "Quince",
    "Custard Apple",
    "Chayote",
    "Pepino",
    "Jujube",
    "Miracle Fruit",
    "Salak",
    "Sapodilla",
    "Sapote",
    "Soursop",
    "Surinam Cherry",
    "Tamarillo",
    "Wax Jambu",
    "Yangmei",
    "Yantok",
    "Yuzu",
    "Zalzalak",
    "African Cherry Orange",
    "African Mango",
    "Barbadine",
    "Bignay",
    "Borojo",
    "Breadfruit",
    "Burah Fruit",
    "Burdekin Plum",
    "Canistel",
    "Carob",
    "Cashew Apple",
    "Cempedak",
    "Chebulic Myrobalan",
    "Cloudberry",
    "Cocky Apple",
    "Crabapple",
    "Crowberry",
    "Damson",
    "Dead Man's Fingers",
    "Duku",
    "Elderberry",
    "Emu Apple",
    "Entawak",
    "Finger Lime",
    "Gabiroba",
    "Genip",
    "Grumichama",
    "Hala Fruit",
    "Horned Melon",
    "Ilama",
    "Jaboticaba",
    "Jujube",
    "Kepel Fruit",
    "Kiwano",
    "Kundong",
    "Kutjera",
    "Langsat",
    "Lingonberry",
    "Longan",
    "Lulo",
    "Mamey Sapote",
    "Mamoncillo",
    "Mangaba",
    "Mangosteen",
    "Maracuja",
    "Midgen Berry",
    "Miracle Berry",
    "Monkey Jack Fruit",
    "Monstera Deliciosa",
    "Mulberry",
    "Mundu",
    "Muntries",
    "Muskmelon",
    "Nannyberry",
    "Native Mulberry",
    "Native Passionfruit",
    "Native Tamarind",
    "Nungu",
    "Otaheite Gooseberry",
    "Oval Kumquat",
    "Pandan",
    "Paw Paw",
    "Peach Palm Fruit",
    "Peruvian Apple Cactus",
    "Pitanga",
    "Poha Berry",
    "Pulasan",
    "Purple Mangosteen",
    "Ramontchi",
    "Raspberry",
    "Red Bayberry",
    "Riberry",
    "Rose Apple",
    "Rowal",
    "Safou",
    "Salak",
    "Salmonberry",
    "Santol",
    "Satsuma",
    "Sea Grape",
    "Shepherd's Plum",
    "Siberian Kiwi",
    "Snake Fruit",
    "Soapberry",
    "Sorbus Americana",
    "Sorbus Aria",
    "Sorbus Aucuparia",
    "Sorbus Decora",
    "Sorbus Devoniensis",
    "Sorbus Domestica",
    "Sorbus Commixta",
    "Sorbus Cashmiriana",
    "Sorbus Chamaemespilus",
    "Sorbus Arizonica",
    "Sorbus Acuparia",
    "Sorbus Anglica",
    "Sorbus Commixta",
    "Sorbus Vilmorinii",
    "Sorbus Tianschanica",
    "Sorbus Tibetica",
    "Sorbus Taxifolia",
    "Sorbus Scalaris",
    "Sorbus Scotica",
    "Sorbus Simensis",
    "Sorbus Rosaefolia",
    "Sorbus Stenophylla",
    "Sorbus Rupicola",
    "Sorbus Rehderiana",
    "Sorbus Sargentiana",
    "Sorbus Redliana",
    "Sorbus Hyrcana",
    "Sorbus Wislica",
    "Sorbus Umbellata",
    "Sorbus Vilmorinii",
    "Sorbus Wilmorinii",
    "Sorbus Wilsoniana",
    "Sorbus Vilmorinii",
    "Sorbus Wilmorinii",
    "Sorbus Wilsoniana",
    "Sorbus Yatungensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Thibetica",
    "Sorbus Umbellata",
    "Sorbus Vilmorinii",
    "Sorbus Wilmorinii",
    "Sorbus Wilsoniana",
    "Sorbus Yatungensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Thibetica",
    "Sorbus Umbellata",
    "Sorbus Vilmorinii",
    "Sorbus Wilmorinii",
    "Sorbus Wilsoniana",
    "Sorbus Yatungensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Thibetica",
    "Sorbus Umbellata",
    "Sorbus Vilmorinii",
    "Sorbus Wilmorinii",
    "Sorbus Wilsoniana",
    "Sorbus Yatungensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Thibetica",
    "Sorbus Umbellata",
    "Sorbus Vilmorinii",
    "Sorbus Wilmorinii",
    "Sorbus Wilsoniana",
    "Sorbus Yatungensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Thibetica",
    "Sorbus Umbellata",
    "Sorbus Vilmorinii",
    "Sorbus Wilmorinii",
    "Sorbus Wilsoniana",
    "Sorbus Yatungensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Thibetica",
    "Sorbus Umbellata",
    "Sorbus Vilmorinii",
    "Sorbus Wilmorinii",
    "Sorbus Wilsoniana",
    "Sorbus Yatungensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Thibetica",
    "Sorbus Umbellata",
    "Sorbus Vilmorinii",
    "Sorbus Wilmorinii",
    "Sorbus Wilsoniana",
    "Sorbus Yatungensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Thibetica",
    "Sorbus Umbellata",
    "Sorbus Vilmorinii",
    "Sorbus Wilmorinii",
    "Sorbus Wilsoniana",
    "Sorbus Yatungensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Thibetica",
    "Sorbus Umbellata",
    "Sorbus Vilmorinii",
    "Sorbus Wilmorinii",
    "Sorbus Wilsoniana",
    "Sorbus Yatungensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Thibetica",
    "Sorbus Umbellata",
    "Sorbus Vilmorinii",
    "Sorbus Wilmorinii",
    "Sorbus Wilsoniana",
    "Sorbus Yatungensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Thibetica",
    "Sorbus Umbellata",
    "Sorbus Vilmorinii",
    "Sorbus Wilmorinii",
    "Sorbus Wilsoniana",
    "Sorbus Yatungensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
    "Sorbus Yunnanensis",
  ];
 //console.log(fruits.length);
 //uppercase
 fruits.forEach(fruit => {
    console.log(fruit.toUpperCase());
  });

//ascendibg
fruits.sort();

// Print each fruit name in uppercase in ascending order
fruits.forEach(fruit => {
  console.log(fruit.toUpperCase());
});

console.log(fruits.includes("Coconut"));
console.log(fruits.indexOf("Coconut"));


const addsagar=fruits.splice(30,306,"sagar");
console.table(fruits);


//descending order 
fruits.sort();

// Reverse the sorted array to get descending order
fruits.reverse();

// Print each fruit name in uppercase in descending order
fruits.forEach(fruit => {
  console.log(fruit.toUpperCase());

});

const originalobject= {
    name:"amrit",
    lastname:"regmi",
    age:23
};
const updatedobject={... originalobject,age:34};
console.log(updatedobject);

